apiVersion: 1

contactPoints:
  - orgId: 1
    name: Alertmanager
    receivers:
      - uid: alertmanager-webhook
        type: webhook
        settings:
          url: http://alertmanager:9093/api/v2/alerts
        disableResolveMessage: false
